"""add time index

Revision ID: 809932e97d97
Revises: c19105c8be7f
Create Date: 2020-04-28 17:28:36.917169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809932e97d97'
down_revision = 'c19105c8be7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assertion_time'), 'assertion', ['time'], unique=False)
    op.create_index(op.f('ix_bounty_time'), 'bounty', ['time'], unique=False)
    op.create_index(op.f('ix_event_time'), 'event', ['time'], unique=False)
    op.create_index(op.f('ix_vote_time'), 'vote', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_time'), table_name='vote')
    op.drop_index(op.f('ix_event_time'), table_name='event')
    op.drop_index(op.f('ix_bounty_time'), table_name='bounty')
    op.drop_index(op.f('ix_assertion_time'), table_name='assertion')
    # ### end Alembic commands ###
