"""add missing address field

Revision ID: c19105c8be7f
Revises: 65fa64085de5
Create Date: 2020-04-28 16:42:51.866933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19105c8be7f'
down_revision = '65fa64085de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_bounty_address'), 'bounty', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bounty_address'), table_name='bounty')
    op.drop_column('bounty', 'address')
    # ### end Alembic commands ###
