"""add missing fields

Revision ID: e6ac484ebe1a
Revises: 65799c004517
Create Date: 2020-05-06 15:53:05.498314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ac484ebe1a'
down_revision = '65799c004517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounty', sa.Column('community', sa.String(), nullable=True))
    op.create_index(op.f('ix_bounty_community'), 'bounty', ['community'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bounty_community'), table_name='bounty')
    op.drop_column('bounty', 'community')
    # ### end Alembic commands ###
